### ISSUE TITLE
get.func is TRUE by default in `getResult.R`

### ISSUE THREAD

**Issue by artur-sannikov** [microbiome/MGnifyR#36]
Contrary to what [docs](https://github.com/microbiome/MGnifyR/blob/master/R/getResult.R#L27) of `getResult()` say, `get.func` [parameter](https://github.com/microbiome/MGnifyR/blob/master/R/getResult.R#L116C1-L120C10) appears to be `TRUE`. When I run from vignette: 
```R
mae <- 
  getResult(
    mg,
    all_accessions,
    bulk_dl = TRUE,
    use.cache = TRUE
  )
```
 it also says "Fetching functional data...".

**Comment by TuomasBorman** [comment]
Thanks, you're correct, I will change that
